# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  solution: '$(Build.SourcesDirectory)/PKHeX-Plugins.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 7.0
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>=6.4.0'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
    git clone -q --depth=5 --branch=net7 https://github.com/kwsch/PKHeX.git $(Build.SourcesDirectory)/PKHeX

- task: VSBuild@1
  continueOnError: true
  inputs:
    solution: '$(Build.SourcesDirectory)/PKHeX/PKHeX.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true
    createLogFile: true

- powershell: |
    $nugetver = (Get-ChildItem "$(UserProfile)/.nuget/packages/pkhex.core" | Sort-Object -Property LastWriteTime -Descending)[0].Name
    New-Item -ItemType Directory -Force -Path "$(UserProfile)\.nuget\packages\pkhex.core\$nugetver\lib\net7.0"
    Copy-Item "$(Build.SourcesDirectory)\pkhex\PKHeX.Core\bin\Release\net7.0\PKHeX.Core.dll" "$(UserProfile)\.nuget\packages\pkhex.core\$nugetver\lib\net7.0"
    Copy-Item "$(Build.SourcesDirectory)\pkhex\PKHeX.Core\bin\Release\net7.0\PKHeX.Core.dll" "$(UserProfile)\.nuget\packages\pkhex.core\$nugetver\lib\net46"
    Copy-Item "$(Build.SourcesDirectory)\pkhex\PKHeX.Core\bin\Release\net7.0\PKHeX.Core.dll" "$(UserProfile)\.nuget\packages\pkhex.core\$nugetver\lib\netstandard2.0"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    createLogFile: true

- task: CmdLine@2
  inputs:
    script: |
      mkdir bin
      xcopy $(Agent.BuildDirectory)\s\AutoLegalityMod\bin\Release\net7.0-windows\AutoModPlugins.dll $(Agent.BuildDirectory)\s\bin

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)\s\bin'
    ArtifactName: 'PKHeX-Plugins'
    publishLocation: 'Container'
